name: CLIP4Clip
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
name: CLIP4Clip
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - asttokens
  - blas
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - comm
  - cpuonly
  - cryptography
  - debugpy
  - decorator
  - entrypoints
  - executing
  - ffmpeg
  - filelock
  - freetype
  - giflib
  - gmp
  - gmpy2
  - gnutls
  - idna
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - jpeg
  - jupyter_client
  - jupyter_core
  - lame
  - lcms2
  - lerc
  - libdeflate
  - libffi
  - libiconv
  - libidn2
  - libjpeg-turbo
  - libpng
  - libsodium
  - libtasn1
  - libtiff
  - libunistring
  - libuuid
  - libwebp
  - libwebp-base
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib-inline
  - mpc
  - mpfr
  - mpmath
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - numpy
  - numpy-base
  - openh264
  - openjpeg
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytorch-mutex
  - pyyaml
  - pyzmq
  - readline
  - requests
  - setuptools
  - six
  - sqlite
  - stack_data
  - sympy
  - tbb
  - tk
  - torchvision
  - tornado
  - traitlets
  - typing_extensions
  - urllib3
  - wheel
  - xz
  - yaml
  - zeromq
  - zlib
  - zstd


